// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhI0GY4aA0AaD0fqAKoelaoErDdwk8bc',
    appId: '1:232670364370:web:c8d979ad43e67e4546a30b',
    messagingSenderId: '232670364370',
    projectId: 'login-page-1d68c',
    authDomain: 'login-page-1d68c.firebaseapp.com',
    storageBucket: 'login-page-1d68c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKw4BvO56MRxRrc2aUuyki5MTR-lJpbFM',
    appId: '1:232670364370:android:6d335b03ae848cf046a30b',
    messagingSenderId: '232670364370',
    projectId: 'login-page-1d68c',
    storageBucket: 'login-page-1d68c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChy5IjY-c24ysMikJm5xDJhLq9bZ-5njc',
    appId: '1:232670364370:ios:586a1e5ec193930546a30b',
    messagingSenderId: '232670364370',
    projectId: 'login-page-1d68c',
    storageBucket: 'login-page-1d68c.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChy5IjY-c24ysMikJm5xDJhLq9bZ-5njc',
    appId: '1:232670364370:ios:03dd83fec8e0eda046a30b',
    messagingSenderId: '232670364370',
    projectId: 'login-page-1d68c',
    storageBucket: 'login-page-1d68c.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
